# permissions for end users to view mysqlbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlbackup-viewer-role
rules:
- apiGroups:
  - db.radondb.com
  resources:
  - mysqlbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.radondb.com
  resources:
  - mysqlbackups/status
  verbs:
  - get
